<?xml version="1.0"?>
<!DOCTYPE suppliers [
    <!ELEMENT suppliers (supplier+)>

    <!ELEMENT supplier (supplierid, distributionarea, product+)>
    <!ELEMENT supplierid (#PCDATA)>
    <!ELEMENT distributionarea (#PCDATA)>

    <!ELEMENT product (product_name, asin, product_url, brand_name, image_url, msrp, sale_price, discount, product_description, date_available, number_reviews, seller_name)>
    <!ATTLIST product instock (Y|N) #REQUIRED>
    <!ATTLIST product productid ID #REQUIRED>

    <!ELEMENT product_name (#PCDATA)>
    <!ELEMENT asin (#PCDATA)>
    <!ELEMENT product_url (#PCDATA)>
    <!ELEMENT brand_name (#PCDATA)>
    <!ELEMENT image_url (#PCDATA)>
    <!ELEMENT msrp (#PCDATA)>
    <!ELEMENT sale_price (#PCDATA)>
    <!ELEMENT discount (#PCDATA)>
    <!ELEMENT product_description (#PCDATA)>
    <!ELEMENT date_available (#PCDATA)>
    <!ELEMENT number_reviews (#PCDATA)>
    <!ELEMENT seller_name (#PCDATA)>
]>
<suppliers>
  <supplier>
    <supplierid>2384</supplierid>
    <distributionarea>Toronto</distributionarea>
    <product instock="Y" productid="SD93">
      <product_name>Ashley Plastic Disposable Ear Loop Elastic 2 Layer Face Mask Blue - 100 Pieces</product_name>
      <asin>B07XRPLXXW</asin>
      <product_url>https://www.amazon.in/Ashley-Plastic-Disposable-Elastic-Layer/dp/B07XRPLXXW/</product_url>
      <brand_name>Ashley</brand_name>
      <image_url>https://images-na.ssl-images-amazon.com/images/I/513GV61ANyL._SL1000_.jpg</image_url>
      <msrp></msrp>
      <sale_price></sale_price>
      <discount></discount>
      <product_description>We Ashley are well-known and distinguished manufacturer of a wide range
        of disposable caps shower cap disposable covers medical masks disposable briefs disposable
        bed sheet. Ashley is committed to achieving 100 % by supplying products according to the
        requirement. We are well equipped with machinery which enables us in maintaining the
        aspects.</product_description>
      <date_available>2019-09-10 00:00:00</date_available>
      <number_reviews>0</number_reviews>
      <seller_name></seller_name>
    </product>
    <product instock="N" productid="B12">
      <product_name>SMARTCARE Face Mask Cloth Tie Green</product_name>
      <asin>B079CHH5M3</asin>
      <product_url>https://www.amazon.in/Smart-Care-Face-Cloth-Green/dp/B079CHH5M3/</product_url>
      <brand_name>SMARTCARE</brand_name>
      <image_url>https://images-na.ssl-images-amazon.com/images/I/61oieimEvzL._SL1200_.jpg</image_url>
      <msrp> 1000.00</msrp>
      <sale_price>250.00</sale_price>
      <discount>75%</discount>
      <product_description>Cloth Face masks. Used in medical dental laboratory food sectors school
        household industry and multi-purpose. Easy breathable effective multilayer bacterial filter.
        Soft lightweight comfortable and easy to wear Smart Care Trust.</product_description>
      <date_available>2018-01-28 00:00:00</date_available>
      <number_reviews>1</number_reviews>
      <seller_name>Aastha Uniform and Overgowns</seller_name>
    </product>
  </supplier>
  <supplier>
    <supplierid>5268</supplierid>
    <distributionarea>Brampton</distributionarea>
    <product instock="Y" productid="Q52">
      <product_name>PrimeStore Reusable Surgeons Cotton Gown Set with Face Mask and Cap Green</product_name>
      <asin>B076GXKW7Z</asin>
      <product_url>https://www.amazon.in/PrimeStore-Premium-quality-Reusable-Surgeons/dp/B076GXKW7Z/</product_url>
      <brand_name>PrimeStore</brand_name>
      <image_url>https://images-na.ssl-images-amazon.com/images/I/61-ypxh9dLL._SL1500_.jpg</image_url>
      <msrp> 1020.00</msrp>
      <sale_price>515.00</sale_price>
      <discount>50%</discount>
      <product_description>Made from highly durable fabric. Finest surgeon gowns have sturdy
        double-stitched seams. Sleeves with stockinette cuffs.</product_description>
      <date_available>2017-10-15 00:00:00</date_available>
      <number_reviews>8</number_reviews>
      <seller_name>New Prime Store</seller_name>
    </product>
  </supplier>
  <supplier>
    <supplierid>3384</supplierid>
    <distributionarea>Ajax</distributionarea>
    <product instock="Y" productid="PS93">
      <product_name>Riderscart Anti Pollution Mask Washable Dust Mask Air Filter Mask for Pollution
        Smoke Allergy Mask with Filter Protect from Virus PM2.5 Unisex SizeBlack with Warranty</product_name>
      <asin>B07G8BHQF6</asin>
      <product_url>
        https://www.amazon.in/Riderscart-Premium-Pollution-Washable-Allergy/dp/B07G8BHQF6/</product_url>
      <brand_name>Riderscart</brand_name>
      <image_url>https://images-na.ssl-images-amazon.com/images/I/51Gqsbd1u1L.jpg</image_url>
      <msrp> 699.00</msrp>
      <sale_price>269.00</sale_price>
      <discount>62%</discount>
      <product_description>The anti-pollution mask is very innovative....which has high filtration
        efficiency can easily filter dust gases pollen and other organic vapors thus protects from
        various respiratory problems or breathing allergies.......It comes with soft nose clip and
        elastic straps so suitable for many face sizes. The exhalation valves are provided to flow
        out the exhaled air for easy breathing. It is washable and reusable. Filter can be easily
        replaced when needed. Recommended for people having respiratory problems and breathing
        allergies......It is compact suitably designed so easy to carry and store. Effectively
        protects from the vehicular pollution and dust on the roads.</product_description>
      <date_available>2018-08-06 00:00:00</date_available>
      <number_reviews>22</number_reviews>
      <seller_name>Riderscart</seller_name>
    </product>
    <product instock="Y" productid="M12">
      <product_name>Bigg Moustache Disposable Face Mask 3 Ply Tie Style Disposable Masks Medical
        Masks Dust Mask Pollution Mask 25 pcs</product_name>
      <asin>B085GL4WXZ</asin>
      <product_url>https://www.amazon.in/Bigg-Moustache-Disposable-Medical-Pollution/dp/B085GL4WXZ/</product_url>
      <brand_name>Bigg Moustache</brand_name>
      <image_url>https://images-na.ssl-images-amazon.com/images/I/61Xl0ng0pEL._SL1000_.jpg</image_url>
      <msrp></msrp>
      <sale_price></sale_price>
      <discount></discount>
      <product_description>Disposable Mouth Masks Professional 3-Layer Thicker Anti Dust Breathable
        Disposable Earloop Face Mask Surgical Mask Our disposable masks are made of three layers of
        purifying dust and skin-friendly filter cloth which gives multiple protection against dust
        and contaminants. Feature: Colour: blue Size:17.5x9.5cm/6.9*3.7 inches FREE SIZE</product_description>
      <date_available>2020-03-03 00:00:00</date_available>
      <number_reviews>0</number_reviews>
      <seller_name></seller_name>
    </product>
  </supplier>
  <supplier>
    <supplierid>9008</supplierid>
    <distributionarea>Toronto</distributionarea>
    <product instock="N" productid="F32">
      <product_name>Antil&apos;s Disposable 3ply Surgical Elastic Face Mask Pack of 10</product_name>
      <asin>B085LPT6MW</asin>
      <product_url>https://www.amazon.in/Antils-Disposable-3ply-Surgical-Elastic/dp/B085LPT6MW/</product_url>
      <brand_name>Antil&apos;s</brand_name>
      <image_url>https://images-na.ssl-images-amazon.com/images/I/41IFHL99ocL.jpg</image_url>
      <msrp> 999.00</msrp>
      <sale_price>449.00</sale_price>
      <discount>55%</discount>
      <product_description>This Face mask is very innovative which has high filtration efficiency
        can easily filter dust gases pollution and other organic vapors thus protects from various
        respiratory problems or breathing allergies. It comes with soft nose clip and elastic straps
        so suitable for many face sizes. The exhalation valves are provided to flow out the exhaled
        air for easy breathing. It is washable and reusable. Filter can be easily replaced when
        needed. Recommended for people having respiratory problems and breathing allergies. It is
        compact suitably designed so easy to carry and store. Effectively protects from the
        vehicular pollution and dust on the roads.</product_description>
      <date_available>2020-03-07 00:00:00</date_available>
      <number_reviews>0</number_reviews>
      <seller_name>Antil&apos;s Hub</seller_name>
    </product>
  </supplier>
</suppliers> 