<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<!DOCTYPE class 
[
  <!ELEMENT class (student+)>
  <!ELEMENT student (firstname, lastname, nickname, marks)>
  <!ATTLIST student rollno CDATA #REQUIRED>
  <!ATTLIST student age CDATA #REQUIRED>
  <!ELEMENT firstname (#PCDATA)>
  <!ELEMENT lastname (#PCDATA)>
  <!ELEMENT nickname (#PCDATA)>
  <!ELEMENT marks (#PCDATA)>
]>
<class>  
  <student rollno="393" age="15">
    <firstname>Dinkar</firstname>    
    <lastname>Kad</lastname>
    <nickname>Dinkar</nickname>
    <marks>85</marks>	 
  </student>
  <student rollno="493" age="16">	 
    <firstname>Vaneet</firstname>
    <lastname>Gupta</lastname>
    <nickname>Vinni</nickname>
    <marks>95</marks>
  </student>
  <student rollno="593" age="16">    
    <firstname>Jasvir</firstname>
    <lastname>Singh</lastname>
    <nickname>Jazz</nickname>
    <marks>90</marks>
  </student>
</class>